// This file is auto-generated by AudioPostprocessor.cs.
// Do not modify this file manually.

using Luna;
using UnityEngine;

public static class R
{
    public static class Audios
    {
            public static Asset<AudioClip> タンホイザーとアイーダメドレー => new("Assets/Common/Commend/Audios/タンホイザーとアイーダメドレー.mp3");
            public static Asset<AudioClip> ハレルヤ => new("Assets/Common/Commend/Audios/ハレルヤ.mp3");
            public static Asset<AudioClip> 威風堂々 => new("Assets/Common/Commend/Audios/威風堂々.mp3");
            public static Asset<AudioClip> 見よ勇者は帰る => new("Assets/Common/Commend/Audios/見よ、勇者は帰る.mp3");
            public static Asset<AudioClip> RouletteBgmLoop => new("Assets/Game/Audios/Roulette_BGM_Loop.mp3");
            public static Asset<AudioClip> ルーレット回転音減速停止 => new("Assets/Game/Audios/ルーレット回転音_減速停止.mp3");
            public static Asset<AudioClip> ルーレット回転音通常 => new("Assets/Game/Audios/ルーレット回転音_通常.mp3");
            public static Asset<AudioClip> ルーレット操作音戻る => new("Assets/Game/Audios/ルーレット操作音_戻る.mp3");
            public static Asset<AudioClip> ルーレット操作音決定 => new("Assets/Game/Audios/ルーレット操作音_決定.mp3");
            public static Asset<AudioClip> ルーレット操作音選択 => new("Assets/Game/Audios/ルーレット操作音_選択.mp3");

    }
}

